name: iOS Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          cd "Task Tracker"
          xcodebuild test \
          -scheme "Task Tracker" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest'
